name: Test Workflow

on:
  workflow_dispatch:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "¡Hola! El workflow está funcionando 🎉"
    
    - name: Check repository
      uses: actions/checkout@v4
    
    - name: List files
      run: |
        echo "Archivos en el repositorio:"
        ls -la
